build:
  id: "{cipher}AYBJ2zGGxESkemFpH/W7LWl6zEUY91GhnA1Ix1Jd+ysMVgGGSQ9fufQxeItdWcPESxbc+c7D8tnqMdJTF2oLAXRni2IKSLqmkbHzORXgWsLGts8D6Zm2FK2CfXVIwMB+jSmtDmWP4IhQ8Zdkff3daTimfklZiIk6B1g8Rh4M6jNMZIUzHJxnkr+2JVnJ/7UJ+UtycRRNPNmXIh10V4iQMXqysFhHL77vyUskCUcDE+6Nps5WZvVL5VLLCubd/sYZ8tjm60OU+j5r5/jJrklPDgobA6+uZvy0DbcFRxaHrgexfFWbZ7SilyAgcvmR9jy1FBpL7SHJ5wMjFfxWf4mCsw2beFzMx8qGE5s2eBXyvvGF3Ljj/fKbqhitNelcy2jyhUXW46f5HaqbChAPYLCAfrgka8SElD/Y7dPh4CGeEo226Vuz7XfKs3pQQOaxFF4jFwVIGShKQlJ7Z5yMDp6GVhpT/DAZelujC2Ph2Uigp5rvMmhnBD0gOAz0zeftCFdiYR1MiWPBOgGtk6m0lK9iO079zx3IRbZ57soTCGQgrc5nDA=="
  version: "{cipher}AYBPPrXrhhNUJmCgRgZ5M/mtk6l25HB/Kyi9K0lDDOb7F5ByTcpBQthUgR7UTYL37gyNaj9KZpgDYXDjMlY6SRwR787aenDO4l9BE25UEDlWqGH2Y6FKZch2GGT/HKDvXw1APm9+XJI5qbpdWkufSCtmFRxAFfTjcQ6M7RtW3uCheILntO7EMtivRfdbszdun+UlYTj9hq0C+fgpvlj47rxeBivKbFHFWdw/RaVxRNvahXRXvrerKg54epRynt71kYro8IccXq+cKRJBrGbMbDIKYUVtiomUMZEMLzWftQQZLqFlOa65npwSqVqfs3svkeFxDCihOKJpFVIYbhuz2j28gWpl+g1uedWgbNZffcB6D7mQq/EVQMrTG/8ssVzHFJNZ9jgG2iT3bXBiCod+QAKc6dwKmQWNE6gv3rvNk/LVQdtVsZAINyHlAVBhXMtOIOH6YpFzzXlmlqsjZv/FToVuUobz/WIjFo9T6HYtFY2sXIz6/Ix05SpOvSdD04HswDRlpLiOwARTCFmyM50Gvpzq9127pHulkp68sI1Nq11feQ=="
  name: "{cipher}AYBlWg2giIt9frbIeWguFi9LauGTxLmk6YNENJKk13J4p0VocO9qbaDVsQzYYCWQlpZRbZqkJgVkTYkgOvYXTAC4dx8lGxtABzgCEFs3LuLtP0dqWf3+IA5RfPW0ReiGonYf3Y8sgserGIvP74xg54oN3lY+nOtVf+zWLr4m4jPJIIb1FWatDWcPUIBM+0u3Npd07ndGXW5iSQpGQqgmORFRwzDmBjhp5M6a7Ag2TIPf8wiZKGIJ0rLgdA1w/gn3r/BnOFQQrDQoXCQu50QjK4NKtGbSxXYQQ4DZBF75RVtjkJF8A2EcKkfybTgLoTBrktprzFGMCYmlY8VWR394iK0TVlq2VUdagI0K96QsGzPV//DI5bjhmZTbGg0OWOzz6kbXIPhRn6zhtat8NEnPh4F/XVoXjBFv6v6qSgRyZkOlMtSMvknMLxdnvTm+/dxDfFX+bXAsSFcck4awy1KalEtE2NmGpRCtOlakBZTd+UlhpYnFWNitscqW+UD+BmSubgh8oybEJZlTlgQTns7qCtEY3HLOryEXIjyjYPh4fqlJNPwAhgEIBVjn+ZZzzpInTM4="

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO #(TRACE, DEBUG, INFO, WARN, ERROR)
    com.info.configdemo.BuildInfoController: DEBUG
  file:
    name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 5MB
      max-history: 7 # It stores them for 7 days
