build:
  id: "{cipher}AYCCjDaWWUiCtpjh+tMu/Jnf1JhzCu4QG02uJSuJxw5iPEAGcC4nrG/RV4HRw4ZXA4PP7e55Z8KvhurtWbPv7Z72ctg52I1ajxweJvy9duYE1OvKvNQyMIqpxWHRfHvKp3KjtocYzOUC2bWC/EwMnfPk1InWaWjpf+QeLPDZ3ynxmIk+o9KZrC/HQlle3fmNvJbmPsi0JWN0a885qS4dtTVhyN9C7MV5pVgSylbi7Q0o21QOFUUM2BKUe5zaX/HTmc2ZQDoLbEOFM8+obKove5hWJ+RCaEwXylISa9FZuAk7+FnrllLdHRq42JE5pGPNp0sAY8EpcZFZiRXV+YACWFQvY6/u0Tg9600ocOnTaP6ODnDaZBWk97IbS6AJr3QckHMKw07Bwg1Pt8BXj5HKQ6TWK+ZK+LC97jRDWdSuH0dypsMFXnsk/BlZa6pY+nap4Nm6zu/D5+2PgB1l1yvlr3MoxnHl9OcXDRxUSbm9iQjiW9qSjbBV4LFysAymN7eteFYiFjIgsAGqLXMe1C4SFD2s4Jfv82LGwcwMnxF1EdrStQ=="
  version: "{cipher}AYBOAZ+maaiUnLFuV0cQ9oJtL4oQrb6ZNGS3ly1/kpvz6erOegEBlLD8PIqcLzdgm3DTMEI1M5NgZsqRKkfeEUeQ1CFSxLS0YiwGK50IX0oYxkVTurw0Z6KVw8MnaQyskgwxaA5O6mf2YzQ3dtWKeluAWDlZYJ6oqbFVEbw4NqKoLHM33C3QGY7EUkGwXK7IGSp7Hff7t/PbGNb2yfKT/eYFYP4VrLW7ux3EqEK5RaKimZg9FJnvFUS6HGoh49QORtpAjUYjfYzeIFD2RDbPMS3FpxjJQ6sAaUOVlpDOLLnWkFSyC8pjkRyWZ8H3jaboQYqHczOJAKoXZGA3QyoaNHoSOp8BcQiv2FPitHqLp/7bajDJ77rZ24cVipLpl/Nokqkkrnbahz54c1wMZ8hbgQ56gcEY328NKZqFOGDrnW0Hmpv+V63Fmzq2BknnhDBJEMSyM8xRTZvdm5neaav21formDtAE28ZC5SCYEbWE0fkRqq3HBk2JJF63XKaOO5TvM15mHrdTC3gBpXUdEUd/h7BpCSh473pnBm234kakBSXWw=="
  name: "{cipher}AYBeWsFnobiHnpaRH4VIp+s8fM66QWATnsZAPiSNORxJkazednCrOmLbJajMK5J90gc1yxxKNBuOd8nZ9zqq/H99t/oOKiJUebxYxgom5w3mYoQk82Mmk2JoW90tJ/9I6Lac04Nj5HjbJX1ASdFxkXznnoHAB46Gt7QhLm10VW5IF56M9dvoDVALRDJQzoC6XXsDCfSO4xeeVTniay9/uO1qmPFRAyUvwq6Itlob1tDJKnD+QLVyfkQdrEx7S3QcK0q53dUZoQOL9FleOqSjFIR/KfZ2R0WBhusbo27amDnG5BIiKLknGcXO3JUHGzTqq6hFRJLGyGNcvg8E2hV79L3qpqQlhtBo0RY/5ZUT9ZMRXZVWo4ZUvmX5ZC/uuwdLx/UeqxVS4MQmr2bcr4QsFP1Id3u3KZwX0+DqihVL2nhW37KjVNX1N3iBIArrvcB6Hej8H3qWPy7yMPyFRFfe18UD2AXHnDOW0H0NlYaWv0blVDvx5aK9kPlcBRY809NvKC+/5YxBo2UHVxF1rKqhwqhbR5gv8id0bKXVhCOGIYRFi9jFRUL4mbZxF3gSOP6Iits="

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
