#Testing filters in yml configuration - configured in java configuration class
# spring:
#  cloud:
#    gateway:
#      server:
#        webflux:
#          routes:
#            - id: product-service
#              uri: lb://PRODUCT-SERVICE
#              predicates:
#                - Path=/products/**
#              filters:
#                - "RewritePath=/products(?<segment>/?.*),/api/products${segment}"
#            - id: user-service
#              uri: lb://USER-SERVICE
#              predicates:
#                - Path=/users/**
#              filters:
#                - "RewritePath=/users(?<segment>/?.*),/api/users${segment}"
#            - id: order-service
#              uri: lb://ORDER-SERVICE
#              predicates:
#                - Path=/cart/**, /orders/**
#              filters:
#                - "RewritePath=/(?<segment>.*),/api/${segment}"
#            - id: eureka-server
#              uri: http://localhost:8761
#              predicates:
#                - Path=/eureka/main
#              filters:
#                - SetPath=/
#            - id: eureka-server-static
#              uri: http://localhost:8761
#              predicates:
#                - Path=/eureka/**

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0 # It means that it will capture 100% of the requests. This should be 10% or 20% (0.1 or 0.2)

logging:
  level:
    root: INFO #(TRACE, DEBUG, INFO, WARN, ERROR)
#    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
#    org.springframework.cloud.gateway: TRACE
  file:
    name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 5MB
      max-history: 7 # It stores them for 7 days

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
