spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/company
    username: "leoga"
    password: "leoga"
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
  cloud:
    function:
      definition: reviewCreated
    stream:
      bindings:
        reviewCreated-in-0:
          destination: rating-topic
          group: company-group
          content-type: application/json
          binder: kafka
      kafka:
        binder:
          brokers: localhost:9092

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: "busrefresh, prometheus"
  tracing:
    sampling:
      probability: 1.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    root: INFO #(TRACE, DEBUG, INFO, WARN, ERROR)
  file:
    name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 5MB
      max-history: 7 # It stores them for 7 days
